# Generated by Django 2.0.5 on 2018-05-13 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('City', models.CharField(max_length=30)),
                ('Bdate', models.DateField()),
                ('sex', models.CharField(max_length=30)),
                ('Id', models.IntegerField()),
                ('cellphone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('users.customuser',),
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
